REM THIS IS MADE BY JULIAN BURGESS OWNER OF MISCHIPS DO NOT COPY!!!
REM THIS IS A FAKE VIRUS BY JULIAN BURGESS
MsgBox "WARNING windows has blocked this file, because it has detected a VIRUS. Do you wish to continue?", 4+48, "Windows virus blocker"
MsgBox "You selected yes, are you sure you want to run this virus? It may severely HARM your computer!", 4+48, "Windows virus blocker"
MsgBox "You selected yes, running virus...", 4+48, "Warning"
msgbox "YOUR COMPUTER HAS NOW BEEN TRASHED BY THE LOLZ VIRUS (:< HAVE FUN!",5+16,"ERROR_CODE: 666"
For i = 1 to 500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
msgbox "LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ LOLZ",5+16,"ERROR_CODE: LOLZ"
Next

